/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AboutIndexRouteImport } from './routes/about/index'
import { Route as EmployersIndexRouteImport } from './routes/employers/index'
import { Route as FindJobsIndexRouteImport } from './routes/find-jobs/index'
import { Route as SignInIndexRouteImport } from './routes/sign-in/index'
import { Route as SignUpIndexRouteImport } from './routes/sign-up/index'
import { Route as AuthenticatedApplicationsIndexRouteImport } from './routes/_authenticated/applications/index'
import { Route as AuthenticatedDashboardIndexRouteImport } from './routes/_authenticated/dashboard/index'
import { Route as AuthenticatedProfileIndexRouteImport } from './routes/_authenticated/profile/index'
import { Route as AuthenticatedProfileOnboardingRouteImport } from './routes/_authenticated/profile/onboarding'
import { Route as AuthenticatedSavedIndexRouteImport } from './routes/_authenticated/saved/index'
import { Route as AuthenticatedSearchIndexRouteImport } from './routes/_authenticated/search/index'
import { Route as AuthCallbackIndexRouteImport } from './routes/auth/callback/index'
import { Route as AuthVerifyEmailIndexRouteImport } from './routes/auth/verify-email/index'
import { Route as JobsJobIdIndexRouteImport } from './routes/jobs/$jobId/index'
import { Route as OnboardingProfileIndexRouteImport } from './routes/onboarding/profile/index'
import { Route as AuthenticatedEmployerOnboardingIndexRouteImport } from './routes/_authenticated/employer/onboarding/index'
import { Route as AuthenticatedJobsJobIdApplyIndexRouteImport } from './routes/_authenticated/jobs/$jobId/apply/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutIndexRoute = AboutIndexRouteImport.update({
  id: '/about/',
  path: '/about/',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployersIndexRoute = EmployersIndexRouteImport.update({
  id: '/employers/',
  path: '/employers/',
  getParentRoute: () => rootRouteImport,
} as any)
const FindJobsIndexRoute = FindJobsIndexRouteImport.update({
  id: '/find-jobs/',
  path: '/find-jobs/',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInIndexRoute = SignInIndexRouteImport.update({
  id: '/sign-in/',
  path: '/sign-in/',
  getParentRoute: () => rootRouteImport,
} as any)
const SignUpIndexRoute = SignUpIndexRouteImport.update({
  id: '/sign-up/',
  path: '/sign-up/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedApplicationsIndexRoute =
  AuthenticatedApplicationsIndexRouteImport.update({
    id: '/applications/',
    path: '/applications/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDashboardIndexRoute =
  AuthenticatedDashboardIndexRouteImport.update({
    id: '/dashboard/',
    path: '/dashboard/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedProfileIndexRoute =
  AuthenticatedProfileIndexRouteImport.update({
    id: '/profile/',
    path: '/profile/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedProfileOnboardingRoute =
  AuthenticatedProfileOnboardingRouteImport.update({
    id: '/profile/onboarding',
    path: '/profile/onboarding',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSavedIndexRoute = AuthenticatedSavedIndexRouteImport.update({
  id: '/saved/',
  path: '/saved/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSearchIndexRoute =
  AuthenticatedSearchIndexRouteImport.update({
    id: '/search/',
    path: '/search/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthCallbackIndexRoute = AuthCallbackIndexRouteImport.update({
  id: '/auth/callback/',
  path: '/auth/callback/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthVerifyEmailIndexRoute = AuthVerifyEmailIndexRouteImport.update({
  id: '/auth/verify-email/',
  path: '/auth/verify-email/',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsJobIdIndexRoute = JobsJobIdIndexRouteImport.update({
  id: '/jobs/$jobId/',
  path: '/jobs/$jobId/',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingProfileIndexRoute = OnboardingProfileIndexRouteImport.update({
  id: '/onboarding/profile/',
  path: '/onboarding/profile/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedEmployerOnboardingIndexRoute =
  AuthenticatedEmployerOnboardingIndexRouteImport.update({
    id: '/employer/onboarding/',
    path: '/employer/onboarding/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedJobsJobIdApplyIndexRoute =
  AuthenticatedJobsJobIdApplyIndexRouteImport.update({
    id: '/jobs/$jobId/apply/',
    path: '/jobs/$jobId/apply/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about/': typeof AboutIndexRoute
  '/employers/': typeof EmployersIndexRoute
  '/find-jobs/': typeof FindJobsIndexRoute
  '/sign-in/': typeof SignInIndexRoute
  '/sign-up/': typeof SignUpIndexRoute
  '/profile/onboarding': typeof AuthenticatedProfileOnboardingRoute
  '/applications/': typeof AuthenticatedApplicationsIndexRoute
  '/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/profile/': typeof AuthenticatedProfileIndexRoute
  '/saved/': typeof AuthenticatedSavedIndexRoute
  '/search/': typeof AuthenticatedSearchIndexRoute
  '/auth/callback/': typeof AuthCallbackIndexRoute
  '/auth/verify-email/': typeof AuthVerifyEmailIndexRoute
  '/jobs/$jobId/': typeof JobsJobIdIndexRoute
  '/onboarding/profile/': typeof OnboardingProfileIndexRoute
  '/employer/onboarding/': typeof AuthenticatedEmployerOnboardingIndexRoute
  '/jobs/$jobId/apply/': typeof AuthenticatedJobsJobIdApplyIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutIndexRoute
  '/employers': typeof EmployersIndexRoute
  '/find-jobs': typeof FindJobsIndexRoute
  '/sign-in': typeof SignInIndexRoute
  '/sign-up': typeof SignUpIndexRoute
  '/profile/onboarding': typeof AuthenticatedProfileOnboardingRoute
  '/applications': typeof AuthenticatedApplicationsIndexRoute
  '/dashboard': typeof AuthenticatedDashboardIndexRoute
  '/profile': typeof AuthenticatedProfileIndexRoute
  '/saved': typeof AuthenticatedSavedIndexRoute
  '/search': typeof AuthenticatedSearchIndexRoute
  '/auth/callback': typeof AuthCallbackIndexRoute
  '/auth/verify-email': typeof AuthVerifyEmailIndexRoute
  '/jobs/$jobId': typeof JobsJobIdIndexRoute
  '/onboarding/profile': typeof OnboardingProfileIndexRoute
  '/employer/onboarding': typeof AuthenticatedEmployerOnboardingIndexRoute
  '/jobs/$jobId/apply': typeof AuthenticatedJobsJobIdApplyIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/about/': typeof AboutIndexRoute
  '/employers/': typeof EmployersIndexRoute
  '/find-jobs/': typeof FindJobsIndexRoute
  '/sign-in/': typeof SignInIndexRoute
  '/sign-up/': typeof SignUpIndexRoute
  '/_authenticated/profile/onboarding': typeof AuthenticatedProfileOnboardingRoute
  '/_authenticated/applications/': typeof AuthenticatedApplicationsIndexRoute
  '/_authenticated/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/_authenticated/profile/': typeof AuthenticatedProfileIndexRoute
  '/_authenticated/saved/': typeof AuthenticatedSavedIndexRoute
  '/_authenticated/search/': typeof AuthenticatedSearchIndexRoute
  '/auth/callback/': typeof AuthCallbackIndexRoute
  '/auth/verify-email/': typeof AuthVerifyEmailIndexRoute
  '/jobs/$jobId/': typeof JobsJobIdIndexRoute
  '/onboarding/profile/': typeof OnboardingProfileIndexRoute
  '/_authenticated/employer/onboarding/': typeof AuthenticatedEmployerOnboardingIndexRoute
  '/_authenticated/jobs/$jobId/apply/': typeof AuthenticatedJobsJobIdApplyIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about/'
    | '/employers/'
    | '/find-jobs/'
    | '/sign-in/'
    | '/sign-up/'
    | '/profile/onboarding'
    | '/applications/'
    | '/dashboard/'
    | '/profile/'
    | '/saved/'
    | '/search/'
    | '/auth/callback/'
    | '/auth/verify-email/'
    | '/jobs/$jobId/'
    | '/onboarding/profile/'
    | '/employer/onboarding/'
    | '/jobs/$jobId/apply/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/employers'
    | '/find-jobs'
    | '/sign-in'
    | '/sign-up'
    | '/profile/onboarding'
    | '/applications'
    | '/dashboard'
    | '/profile'
    | '/saved'
    | '/search'
    | '/auth/callback'
    | '/auth/verify-email'
    | '/jobs/$jobId'
    | '/onboarding/profile'
    | '/employer/onboarding'
    | '/jobs/$jobId/apply'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about/'
    | '/employers/'
    | '/find-jobs/'
    | '/sign-in/'
    | '/sign-up/'
    | '/_authenticated/profile/onboarding'
    | '/_authenticated/applications/'
    | '/_authenticated/dashboard/'
    | '/_authenticated/profile/'
    | '/_authenticated/saved/'
    | '/_authenticated/search/'
    | '/auth/callback/'
    | '/auth/verify-email/'
    | '/jobs/$jobId/'
    | '/onboarding/profile/'
    | '/_authenticated/employer/onboarding/'
    | '/_authenticated/jobs/$jobId/apply/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AboutIndexRoute: typeof AboutIndexRoute
  EmployersIndexRoute: typeof EmployersIndexRoute
  FindJobsIndexRoute: typeof FindJobsIndexRoute
  SignInIndexRoute: typeof SignInIndexRoute
  SignUpIndexRoute: typeof SignUpIndexRoute
  AuthCallbackIndexRoute: typeof AuthCallbackIndexRoute
  AuthVerifyEmailIndexRoute: typeof AuthVerifyEmailIndexRoute
  JobsJobIdIndexRoute: typeof JobsJobIdIndexRoute
  OnboardingProfileIndexRoute: typeof OnboardingProfileIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about/': {
      id: '/about/'
      path: '/about'
      fullPath: '/about/'
      preLoaderRoute: typeof AboutIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employers/': {
      id: '/employers/'
      path: '/employers'
      fullPath: '/employers/'
      preLoaderRoute: typeof EmployersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/find-jobs/': {
      id: '/find-jobs/'
      path: '/find-jobs'
      fullPath: '/find-jobs/'
      preLoaderRoute: typeof FindJobsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in/': {
      id: '/sign-in/'
      path: '/sign-in'
      fullPath: '/sign-in/'
      preLoaderRoute: typeof SignInIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-up/': {
      id: '/sign-up/'
      path: '/sign-up'
      fullPath: '/sign-up/'
      preLoaderRoute: typeof SignUpIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/applications/': {
      id: '/_authenticated/applications/'
      path: '/applications'
      fullPath: '/applications/'
      preLoaderRoute: typeof AuthenticatedApplicationsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard/': {
      id: '/_authenticated/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof AuthenticatedDashboardIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/profile/': {
      id: '/_authenticated/profile/'
      path: '/profile'
      fullPath: '/profile/'
      preLoaderRoute: typeof AuthenticatedProfileIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/profile/onboarding': {
      id: '/_authenticated/profile/onboarding'
      path: '/profile/onboarding'
      fullPath: '/profile/onboarding'
      preLoaderRoute: typeof AuthenticatedProfileOnboardingRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/saved/': {
      id: '/_authenticated/saved/'
      path: '/saved'
      fullPath: '/saved/'
      preLoaderRoute: typeof AuthenticatedSavedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/search/': {
      id: '/_authenticated/search/'
      path: '/search'
      fullPath: '/search/'
      preLoaderRoute: typeof AuthenticatedSearchIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/auth/callback/': {
      id: '/auth/callback/'
      path: '/auth/callback'
      fullPath: '/auth/callback/'
      preLoaderRoute: typeof AuthCallbackIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/verify-email/': {
      id: '/auth/verify-email/'
      path: '/auth/verify-email'
      fullPath: '/auth/verify-email/'
      preLoaderRoute: typeof AuthVerifyEmailIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs/$jobId/': {
      id: '/jobs/$jobId/'
      path: '/jobs/$jobId'
      fullPath: '/jobs/$jobId/'
      preLoaderRoute: typeof JobsJobIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/profile/': {
      id: '/onboarding/profile/'
      path: '/onboarding/profile'
      fullPath: '/onboarding/profile/'
      preLoaderRoute: typeof OnboardingProfileIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/employer/onboarding/': {
      id: '/_authenticated/employer/onboarding/'
      path: '/employer/onboarding'
      fullPath: '/employer/onboarding/'
      preLoaderRoute: typeof AuthenticatedEmployerOnboardingIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/jobs/$jobId/apply/': {
      id: '/_authenticated/jobs/$jobId/apply/'
      path: '/jobs/$jobId/apply'
      fullPath: '/jobs/$jobId/apply/'
      preLoaderRoute: typeof AuthenticatedJobsJobIdApplyIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedProfileOnboardingRoute: typeof AuthenticatedProfileOnboardingRoute
  AuthenticatedApplicationsIndexRoute: typeof AuthenticatedApplicationsIndexRoute
  AuthenticatedDashboardIndexRoute: typeof AuthenticatedDashboardIndexRoute
  AuthenticatedProfileIndexRoute: typeof AuthenticatedProfileIndexRoute
  AuthenticatedSavedIndexRoute: typeof AuthenticatedSavedIndexRoute
  AuthenticatedSearchIndexRoute: typeof AuthenticatedSearchIndexRoute
  AuthenticatedEmployerOnboardingIndexRoute: typeof AuthenticatedEmployerOnboardingIndexRoute
  AuthenticatedJobsJobIdApplyIndexRoute: typeof AuthenticatedJobsJobIdApplyIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedProfileOnboardingRoute: AuthenticatedProfileOnboardingRoute,
  AuthenticatedApplicationsIndexRoute: AuthenticatedApplicationsIndexRoute,
  AuthenticatedDashboardIndexRoute: AuthenticatedDashboardIndexRoute,
  AuthenticatedProfileIndexRoute: AuthenticatedProfileIndexRoute,
  AuthenticatedSavedIndexRoute: AuthenticatedSavedIndexRoute,
  AuthenticatedSearchIndexRoute: AuthenticatedSearchIndexRoute,
  AuthenticatedEmployerOnboardingIndexRoute:
    AuthenticatedEmployerOnboardingIndexRoute,
  AuthenticatedJobsJobIdApplyIndexRoute: AuthenticatedJobsJobIdApplyIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AboutIndexRoute: AboutIndexRoute,
  EmployersIndexRoute: EmployersIndexRoute,
  FindJobsIndexRoute: FindJobsIndexRoute,
  SignInIndexRoute: SignInIndexRoute,
  SignUpIndexRoute: SignUpIndexRoute,
  AuthCallbackIndexRoute: AuthCallbackIndexRoute,
  AuthVerifyEmailIndexRoute: AuthVerifyEmailIndexRoute,
  JobsJobIdIndexRoute: JobsJobIdIndexRoute,
  OnboardingProfileIndexRoute: OnboardingProfileIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
